### PR TITLE
JIRA 745 - modifying center setting notifications to have a type field

### PR DESCRIPTION
**Pull request by lsemesky**
@aml-development/ozp-backend-team 
Requires 
- ozp-react-commons branch orgstewardNotifications https://github.com/aml-development/ozp-react-commons/pull/105
- ozp-backend branch orgstewardNotification (no s at the end) https://github.com/aml-development/ozp-backend/pull/375

Use Case:
- An admin has the ability to send out a notification to all Content Stewards, notifying them to review their org's Listings and make any necessary changes.
- Content Steward updates Listing as needed via Create New Listing Form (the usual means of updating listings)
- Content Steward and listing owner(s) are notified when listing has been updated and approved

Acceptance Criteria:
- Only admins can send notifications to content stewards
- All content stewards receive the notification to update their apps
- Only content stewards receive the "update app" notification type
- Content stewards can click on a link in the in-site notification to go to the same Listing Management Recent Activity tab. (I chose this tab because all org stewards will have it and they can easily go to published listings from overview list on the left. They can also see which ones have been updated recently)
- The system notification type still functions as before there was no "Type" dropdown

To test:
As bigbrother, 

1. Go to Center Settings (from the dropdown menu)
2. Go to the Notifications Tab
3. Select the Update Request type
4. See that the Notification text is populated with a default message (you can change this message if you like)
5. Set expires on date
6. Press send

Login as david, julia, obrien and wsmith to make sure that they have received the message and that it has the link as detailed in acceptance criteria

bigbrother should not receive the notification
hodor should not receive the notification
jones should not receive the notification

### CODE REVIEW

**Comment by mleeBoeing** [comment]
1. Logged in as obrien
2. Went to Listing Management from drop down menu on top right
3. Clicked 'See More' in notifications drop down
4. Clicked on 'Go to Listing Management' link
5. In the background you can see the page changes. However, once you click out of the 'See More' notifications modal, URL changes back to 'My Listings'

**Comment by blynch11p** [comment]
I can not reproduce the error @mleeBoeing found.  Can someone else also look?

Otherwise, the notification sends, org stewards (and not regular users) see the message, and the link in the message take them to the Listing Management page.

👍

**Comment by rkenyon1969** [comment]
I'm testing now

**Comment by mleeBoeing** [comment]
Most likely issues with my local box as machine was kickstarted that day

**Comment by rkenyon1969** [comment]
@mleeBoeing - please test again before we merge

**Comment by blynch11p** [comment]
Update - Bug is reproducible. 
Additionally, closing the Notification modal, going to another tab in the user-managment url root, and opening the Notifications modal again, results in not being able to close the Notification modal.

**Comment by rkenyon1969** [comment]
@blynch11p, @mleeBoeing - I pulled MLs branch and tested with BLs OZP-RC #106 branch.

:+1:

**Comment by blynch11p** [comment]
👍 

I'm going to close this PR, referencing https://github.com/aml-development/ozp-center/pull/900 and merge in #900

**Pull request closed without merging**
