### PR TITLE
Change styling of FOUO bar in Tags

### PR DESCRIPTION
**Pull request by mleeBoeing**
Change styling of FOUO bar in Tags in Create Listing

### CODE REVIEW

**Comment by blynch11p** [comment]
:+1:   Doesn't look like an error anymore.

**Comment by rkenyon1969** [comment]
Please don't merge yet. Clarifying a customer requirement with Ashley.

**Comment by rkenyon1969** [comment]
requirement clarified.

I would remove white space character after "small" if not needed:
21 ...<p className="FOUOwarning small ">...

:+1:

**Comment by rkenyon1969** [comment]
requirement clarified.

I would remove white space character after "small" if not needed:
`21 ...<p className="FOUOwarning small ">...`

:+1:

**Pull request merged**
