### PR TITLE
Updating the notification display page to use the HTML formatted mess…

### PR DESCRIPTION
**Pull request by blynch11p**
…ages in the database.

@lsemesky @mleeBoeing @mannyrivera2010 @J-Fid @rkenyon1969 
Need 'syntaxy' branch from ozp-backend.

To test:
Open an Application
Edit the Application (Fields such as Listing Type, Categories, Tags, Description)
Save the edits
Re-open the application.
Click the Send Notifications tab

screenshot from 2017-06-05 15-01-02

### CODE REVIEW

**Comment by J-Fid** [comment]
I have tested this and it works locally.  However, the Travis CI build failed.

**Comment by blynch11p** [comment]
I rerean the Travis build and it passed.

**Comment by J-Fid** [comment]
:+1:

**Comment by lsemesky** [comment]
:+1: shows up in notification dropdown and notification tab

**Pull request merged**
