### PR TITLE
enhance(tags): Increase tag length to 30 #719

### PR DESCRIPTION
**Pull request by lsemesky**
#719 - increased front end tag size to 30 and added wrapping style to tag container
@akonsowski @blynch11p

### CODE REVIEW

**Comment by lsemesky** [comment]
@skhtet

**Comment by lsemesky** [comment]
@akonsowski

**Comment by lsemesky** [comment]
@blynch11p @rkenyon1969

**Comment by rkenyon1969** [comment]
:+1:

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
