### PR TITLE
fix(index):admin tab will not display for non admin users and will al…

### PR DESCRIPTION
**Pull request by akonsowski**
…so not display a hyperlink for owners in details tab

### CODE REVIEW

**Comment by akonsowski** [comment]
@wski @clarkjefcoat @rkenyon1969

**Comment by wski** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Make changes as discussed before accepting.

**Comment by wski** [comment]
@akonsowski can you verify I've added everything you had locally?

**Comment by clarkjefcoat** [comment]
I still don't understand what this code does.  Please test all of the following scenarios before accepting:

A normal user with the anonymize function set to return True and the user is not the owner
An admin user with the anonymize function set to return True and the user is not the owner
A normal user with the anonymize function set to return False and the user is not the owner
An admin user with the anonymize function set to return False and the user is not the owner
A normal user with the anonymize function set to return True and the user is the owner
An admin user with the anonymize function set to return True and the user is the owner
A normal user with the anonymize function set to return False and the user is the owner
An admin user with the anonymize function set to return False and the user is the owner

**Comment by akonsowski** [comment]
@skhtet

**Comment by skhtet** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Pull request merged**
