### PR TITLE
fix(all listings grid view): Applications are not loaded all at once #135

### PR DESCRIPTION
**Pull request by lsemesky**
Needs GridChange branch to work.

### CODE REVIEW

**Comment by akonsowski** [comment]
@blynch11p

**Comment by akonsowski** [comment]
:+1:

**Comment by blynch11p** [comment]
Feed some feedback to @akonsowski for future thoughts (CSV export/loading indicator) but this is good.  It's FAST!

:+1:

**Comment by blynch11p** [comment]
:+1:

**Pull request merged**
