### PR TITLE
Allow ability to delete Notification in Center Settings

### PR DESCRIPTION
**Pull request by mleeBoeing**
As an admin, I want the ability to delete notifications so that I can manage active and past notification lists.

Acceptance Criteria:
Delete option appears next to notification on Center Settings>Notifications page
When user selects to delete the notification will be permanently deleted

### CODE REVIEW

**Comment by blynch11p** [comment]
Need a confirmation dialog box.  The delete icon is too close to the resend icon.

**Comment by mleeBoeing** [comment]
Added confirmation dialog box and confirmation window that notification has been deleted. Behavior similar to deleting a listing.

**Comment by seenusuvarna** [comment]
Cancelling a Delete prevents one from deleting the notification again until the page is refreshed.

**Comment by mleeBoeing** [comment]
Cancellation issue fixed. Removed secondary popup as well.

**Pull request merged**
