### PR TITLE
feat(listing management): add ability to sort list view

### PR DESCRIPTION
**Pull request by irizvifearless**
AMLNG-858

**Description**     
As a user, I would like all Listing Management tabs to have sort order dropdown option to reorder results and the default sort order to be last modified.

**Acceptance Criteria**   
- when a user clicks on sub tab all results will have the same sort order
- sort order will be last modified
- each tab will have sort order dropdown option to reorder results

For now, the sort options are Last Modified, Newest, Title: A to Z, Title: Z to A, Rating: Low to High, Rating: High to Low, Status.  If no sort option is selected, the backend sort defaults to last modified.
 
**How to test code**    
Pull `listing_default_sort` from ozp-backend
Pull `listing_mgmt_sortable_grid` from ozp-center

Go to Listing Management
Verify Acceptance Criteria on the list view of both the All Center Listings and My Listings tabs

### CODE REVIEW

**Comment by mleeBoeing** [comment]
Need to account for lowercase and uppercase for alphabetical sorting. Otherwise, looks good.

**Comment by irizvifearless** [comment]
@mleeBoeing Implemented case-insensitive sorting for the title field.  I updated the back-end branch `listing_default_sort` so that the change is also reflected when the TableView does its sorting

**Comment by mleeBoeing** [comment]
:+1:

**Comment by blynch11p** [comment]
Functionality is fine, but I'm seeing a style issue on the menu because of the margin-top.
screenshot from 2017-12-28 13-10-30

**Comment by irizvifearless** [comment]
@blynch11p good catch!  I committed a fix for that issue

**Comment by blynch11p** [comment]
👍

**Pull request merged**
