### PR TITLE
feat(feedback): allow thumbs up/down for recommended listings in storefront

### PR DESCRIPTION
**Pull request by mleeBoeing**
Simple, one click step for the user to provide feedback
Negative feedback of a recommendation will remove that recommendation from the user's list.
Piwik should also track when you give a feedback to a recommendation

Must use this branch: https://github.com/aml-development/ozp-backend/pull/356
Make sure to do ```make dev``` & ```make reindex_es```

### CODE REVIEW

**Comment by blynch11p** [comment]
Or... @rkenyon1969 :)

screenshot from 2017-09-28 13-07-52

**Comment by mleeBoeing** [comment]
image

**Comment by mleeBoeing** [comment]
Need to pull from backend again.

**Comment by rkenyon1969** [comment]
screenshot from 2017-09-28 20-31-42

@mleeBoeing - Please make "Not Helpful" appear on one line

**Comment by mleeBoeing** [comment]
@rkenyon1969 that has been fixed already. you need to pull again from this branch

**Comment by rkenyon1969** [comment]
Need change mouse over to include white outline to be consistant:

screenshot from 2017-09-29 17-54-10

screenshot from 2017-09-29 17-55-10

**Comment by rkenyon1969** [comment]
Same with if selected - consistent (yellow fill):

screenshot from 2017-09-29 18-10-19

**Comment by rkenyon1969** [comment]
I think we should return feedback buttons after a user clicks up/down. Netflix allows user to select/change:

screenshot from 2017-10-03 18-44-29

screenshot from 2017-10-03 18-44-45

screenshot from 2017-10-03 18-45-23

**Comment by rkenyon1969** [comment]
@mleeBoeing @lsemesky @flesher1 @blynch11p 

**Question:** Should we keep recommended listing in queue when user thumbs down or remove? 

I'm on the fence. Removing allows user to view additional recommendation, but what if users changes their mind?

Thoughts?

**Comment by lsemesky** [comment]
@rkenyon1969 I believe we should keep the requirements as they are. Ultimately there should be undo actions for mistakes being made and there was talk of being able to manage bookmarks and thumbed up/down apps from another screen but that is out of scope for this ticket.

**Comment by mleeBoeing** [comment]
You will need to pull the new icon dependency.
https://github.com/aml-development/ozp-icons/pull/9

This will include the yellow filled icons

**Comment by rkenyon1969** [comment]
@lsemesky - ability to manage bookmarks/thumbs will be a good addition. I'm concerned about potential performance issues on the customer network that would affect the UX. Maybe we don't remove the listing until the user refreshes/returns-to the page?

**Comment by blynch11p** [comment]
Positive Feedback indicates a thumbs up and maintains state after a page refresh.
Initial negative feedback indicates a thumbs down, and will remove that recommendation after a page reload.
Icons are consistent.
Tooltips are consistent.

👍

**Comment by rkenyon1969** [comment]
1. pulled branch
2. reviewed code
3. tested

:+1:

**Pull request merged**
