### PR TITLE
enhancement(style): updated styles for hovering typeahead suggestions aml-159

### PR DESCRIPTION
**Pull request by lsemesky**
@blynch11p 
@akonsowski 
@skhtet

### CODE REVIEW

**Comment by blynch11p** [comment]
:+1: for mouseover styles
Thoughts about up/down arrow select styles?

**Comment by blynch11p** [comment]
:+1: for all style additions

**Comment by lsemesky** [comment]
Can anyone thumb this up? It's a very simple change. @rkenyon1969 @mannyrivera2010 @J-Fid @seenusuvarna

**Comment by seenusuvarna** [comment]
:+1:  Looks good to me.

**Pull request merged**
