### PR TITLE
Stop and show warning if a category has existing listings and is abou…

### PR DESCRIPTION
**Pull request by mleeBoeing**
Acceptance Criteria -
If category that is being deleted is the only category listed to some of the app listings the admin should be made aware in order to reassign a new category to it.

### CODE REVIEW

**Comment by blynch11p** [comment]
Is it possible to get the "cannot delete" notice prior to clicking the modal's Delete? (is it easy to correct the "Can not" to be "Cannot"?)
Also, after the notice pops up the delete button is still there.

However, this does work and stop the user from removing a category.  And I know this won't be used by a lot of people.

@rkenyon1969, thoughts on if this is fine as-is if the level of effort involved regarding my remarks above is more than a few minutes of work?

**Comment by mleeBoeing** [comment]
Error message change PR link: https://github.com/aml-development/ozp-backend/pull/330

**Comment by rkenyon1969** [comment]
I agree with Brian's points. I suggest doing the following:

1. User selects category and then delete
2. if(listings) then modal with just warning message (w/ "Cannot") and cancel button (not delete button)
3. If(!listings) then normal delete modal

Alternative Message: "The category xxx cannot be deleted. The category has xx listings associated with it."

Thoughts?

**Comment by mleeBoeing** [comment]
If this feature will be used only once or twice, in my opinion the cost benefit is not worth.

**Comment by blynch11p** [comment]
:+1:

**Comment by rkenyon1969** [comment]
I agree with Brian's last point. :+1:

**Pull request merged**
