### PR TITLE
feat(delete): Allow admin and org stewards to delete without pending …

### PR DESCRIPTION
**Pull request by mleeBoeing**
**AMLNG-315**

Right now the app is inconsistent with the way admins and org stewards delete apps. On some screens they are forced through the pending deletion workflow process and other screens ( Listing Management View) they can delete without going through the pending deletion process.
 
Acceptance Criteria:
Admins and Org Stewards don't need to go through the Pending Deletion Workflow.
Only App Owners need an approval/rejection from either Org Steward/Admin before an App Listing is deleted.

@blynch11p @cwilliams2017 @flesher1 @lsemesky @mannyrivera2010 @rkenyon1969 @skhtet @tdressel

### CODE REVIEW

**Comment by mleeBoeing** [comment]
Updated

**Comment by rkenyon1969** [comment]
@mleeBoeing - How does removing the authorization fix it?

**Comment by rkenyon1969** [comment]
Per our conversation yesterday, I can only find one occurrence of UserRoleMixin.OrgSteward. If your results are the same, lets fix this issue and return the authorization check. - thxs,

**Comment by mleeBoeing** [comment]
Please review again. Authorization kept in place

**Comment by rkenyon1969** [comment]
@mleeBoeing 

**Bug:**
STR - 
1. login as julia
2. select listing to delete
3. delete
4. click delete on pop-up confirmation modal
5. click ok on pop-up deletion complete modal

Result - user remains on page with deleted listing still showing
Expected Result - user remains on page w/out deleted listing showing

**Comment by blynch11p** [comment]
Bug above is fixed
Admin can delete
Regular user can only pend
👍

**Comment by rkenyon1969** [comment]
@mleeBoeing - Bug is fixed, but delay may be an issue on customer's network.

@tdressel - please keep this in mind when testing.


:+1:

**Pull request merged**
