### PR TITLE
feat(listing management): add load indicators in listing management

### PR DESCRIPTION
**Pull request by irizvifearless**
closes AMLNG-805, 806, and 807

**Description**
Update page loading process for Listing Management>My Listings, All Center Listings, and Recent Activity to use the same loading indicator as when the center page first loads.

**Acceptance Criteria**
Use site data loading indicator image as placeholder until result set is displayed
Same layout as center page
API calls (search, filtering, load more, etc) use load indicator
Both list and table views use load indicator

**How to test code**
Pull branch amlng-805-806-807

### CODE REVIEW

**Comment by irizvifearless** [comment]
One idea @mannyrivera2010 mentioned was not showing the "Loading..." title by default and instead showing a plain spinner with no text.  Thoughts?

**Comment by blynch11p** [comment]
> One idea @mannyrivera2010 mentioned was not showing the "Loading..." title by default and instead showing a plain spinner with no text. Thoughts?

Maybe make the default prop blank, and pass in text to LoadIndicator in situations where we want text.


I'm also having an issue with this branch on Deleting listings:
In My Listings (just use an admin - like bigbrother), delete a listing.  It doesn't go away.
In the master branch it does.


Otherwise, I like the user being provided visuals on what's going on.

**Comment by irizvifearless** [comment]
I resolved the merge conflicts, so this branch should be consistent with master now.  By popular demand, I also got rid of the 'Loading...' default title.

**Comment by blynch11p** [comment]
👍

**Comment by rkenyon1969** [comment]
:+1:

**Pull request merged**
