### PR TITLE
Initial commit to add subscription link within tag box

### PR DESCRIPTION
**Pull request by mleeBoeing**
Enhance design of tag field to include subscribe link within tag box

1. Login to center
2. Search via by tag, should see Subscribe link implemented within the box

https://jira.di2e.net/browse/AMLNG-569

### CODE REVIEW

**Comment by blynch11p** [comment]
:+1: 

Subscribe link is inside the box with the tag and separated with a pipe ( | ).
Subscribe link works

**Comment by rkenyon1969** [comment]
:-1: 

- reviewed code :+1: 
- reviewed design :-1: 
- tested link :+1: 

Please contact me to review design. - thank you,

**Comment by rkenyon1969** [comment]
:+1: 

- reviewed design :+1:

**Comment by blynch11p** [comment]
Extra spacing is fine.  Color choice seems random.  We don't use orange anywhere else that I've seen.

The hex code for our star rating is #ecc44d

**Comment by rkenyon1969** [comment]
I like #ecc44d

screenshot from 2017-07-11 17-24-46


Makes it easier to read

**Comment by blynch11p** [comment]
:+1:

**Pull request merged**
