### PR TITLE
feat(Private Listings): Added private listings back in

### PR DESCRIPTION
**Pull request by wski**
#704
@rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @rkenyon1969 @akonsowski @mannyrivera2010

### CODE REVIEW

**Comment by akonsowski** [comment]
:+1:

**Comment by wski** [comment]
:+1:

**Comment by akonsowski** [comment]
@wski i dont think that counts

**Comment by mannyrivera2010** [comment]
:+1:

**Pull request merged**
