### PR TITLE
726 carousel scroll fix

### PR DESCRIPTION
**Pull request by lsemesky**
@blynch11p @mannyrivera2010 @skhtet

### CODE REVIEW

**Comment by lsemesky** [comment]
@mannyrivera2010 @skhtet @blynch11p @rkenyon1969

**Comment by lsemesky** [comment]
@mannyrivera2010 @skhtet @blynch11p  sorry I closed this before.

**Comment by blynch11p** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
In reference to #729 

:+1:

**Pull request merged**
