### PR TITLE
Fix Lo to Hi issue with total ratings

### PR DESCRIPTION
**Pull request by mleeBoeing**
Fix sort by issue when doing Ratings -> Low to High. If the ratings were equals, the tie breaker would be the total # reviews (most would show up first). Now it should be the opposite (most total # reviews should show last).

### CODE REVIEW

**Comment by blynch11p** [comment]
Low to High sort order appears to be more in line with what's expected.
:+1:

**Comment by rkenyon1969** [comment]
1. Pulled branch
2. reviewed code
3. tested

- most total # reviews should show last 
- L-H is the reverse order of H-L/MP :+1: 

:+1:

**Comment by rkenyon1969** [comment]
@J-Fid - what do you mean by "when a change is made"? - thanks,

**Comment by J-Fid** [comment]
@rkenyon1969 Reviewing a listing causing its rating to change.  Michael just put in a fix for the the drop down bar, and I'll discuss it with him when he comes back from lunch.

**Pull request merged**
