### PR TITLE
fix: Selecting the center icon now takes the user to the Center Homepage.

### PR DESCRIPTION
**Pull request by J-Fid**
Please Review:
@lsemesky 
@mleeBoeing 
@mannyrivera2010 
@blynch11p 

To test, enter something in the search box.  Afterwards, select the center icon to return to the center homepage.

### CODE REVIEW

**Comment by lsemesky** [comment]
This technically works but I don't like the solution because it forces an entire refresh of the page which causes all the info to need to be downloaded again instead of making use of React's caching. Ideally this link would work the same as clicking the "Center Home" in the sidebar. (Take a look at /app/js/components/discovery/Sidebar) 

If others think it's not worth the effort of refactoring this (as it would require more knowledge of react), I would consider at least making it consistent with the other header links by changing line 9 from 
```var { HUD_URL, METRICS_URL, WEBTOP_URL, DEVELOPER_RESOURCES_URL} = require('ozp-react-commons/OzoneConfig');``` 
to 
```var { HUD_URL, METRICS_URL, WEBTOP_URL, DEVELOPER_RESOURCES_URL, CENTER_URL} = require('ozp-react-commons/OzoneConfig');```

and change ```href=''``` to ```href={CENTER_URL}```

**Comment by lsemesky** [comment]
If @blynch11p or @rkenyon1969 decides it's fine as-is I am fine thumbing up as it works fine

**Comment by lsemesky** [comment]
Just read the Jira ticket and noticed it does have acceptance requirement as this icon doing the same thing as clicking the logo, which it does. I also believe the behavior of the logo should change as well, but perhaps that's for a different tech debt ticket.

**Comment by blynch11p** [comment]
Laura makes good points.  What this ticket brings up is the fact the the URL is not correctly updated when filtering the home page by Organization, Listing Type, or Category.  The routing for those all work (there is a `Share` link available after running any of these filters that can be copy/pasted and the correct page is built).  Though, clicking the shopping bag after using that link does not correctly take the user back to the Center home even though the URL updates.

I think I may just lean toward this fix being OK.  The functionality is consistent with the Logo, and all of the links across the top (HUD/Webtop) are also 'external links' that cause the full page to load.

I'm a :+1: unless @rkenyon1969 has a different weigh-in.

**Comment by rkenyon1969** [comment]
Please let me review before proceeding. I will take a look after stand-up. - thank you,

**Comment by rkenyon1969** [comment]
I agree with Laura and Brian - Fixes current issue and we can discuss future enhancements later.

- Pulled the branch
- Reviewed the code
- Tested successfully

:+1:

**Comment by rkenyon1969** [comment]
Spoke w/ Brian. Need to create additional ticket for backlog to address remaining issue (see below):

- Pulled the branch
- Reviewed the code
- Tested successfully

:+1: 


**Remaining Issues:**
- Listing API called twice
- Do we need if(!_listing)
- What is "new Listing({ owners: [this.currentUser] })" for?

**Pull request merged**
