### PR TITLE
fix(package):fs package is now part of the npm core

### PR DESCRIPTION
**Pull request by akonsowski**
having the fs package install was breaking travis build
[source](https://github.com/npm/npm/issues/13743)

### CODE REVIEW

**Comment by akonsowski** [comment]
@wski @rkenyon1969 @skhtet

**Comment by wski** [comment]
:+1:

**Comment by skhtet** [comment]
:+1:

**Comment by wski** [comment]
Agreed that we should not have been requiring built in modules from the start. Go ahead and merge IMO.

**Pull request merged**
