### PR TITLE
Have loading indicator for storefront

### PR DESCRIPTION
**Pull request by mleeBoeing**
Create a loading indicator when items are loading on storefront. The indicator will be a circle spinning infinitely.

### CODE REVIEW

**Comment by blynch11p** [comment]
Need to handle Failed loads as well.  Otherwise the spinner remains.

**Comment by mleeBoeing** [comment]
Updated

**Comment by blynch11p** [comment]
Looks good.  Errors are handled as well. :+1:

**Comment by rkenyon1969** [comment]
1. pulled code
2. reviewed code
3. tested

:+1:

**Pull request merged**
