### PR TITLE
Recommendations

### PR DESCRIPTION
**Pull request by lsemesky**
adding recommendation modal on front page. Has commented out code for similar applications in quickview

@mleeBoeing @blynch11p

### CODE REVIEW

**Comment by lsemesky** [comment]
If changes need to be made to this code feel free to checkout the branch and make them

**Comment by lsemesky** [comment]
Also whoever does the second :+1:, please merge the branch

**Comment by blynch11p** [comment]
:+1:

**Comment by mleeBoeing** [comment]
:+1:

**Pull request merged**
